name: Update docs

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/docs/**'

jobs:
  test_shit:
    runs-on: ubuntu-latest
    steps: 
      - name: 'Log'
        run: echo 'hello'
  